
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/metaparticle-io/metaparticle-ast"
  version = "0.2.0"

# had to override this version because of https://github.com/golang/dep/issues/1415
[[override]]
  name = "github.com/docker/distribution"
  revision = "f4118485915abb8b163442717326597908eee6aa"


[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "12.2.0-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "9.6.0"